from model.keyboard import DisplayKeys, KeyboardKeys, MenuKeys, MovementKeys, PhysicsKey

default_keyboard_mapping: dict[KeyboardKeys, str] = {
    MenuKeys.QUIT: "q",
    MenuKeys.SWITCH_3D_MODE: "2",
    MenuKeys.SWITCH_2D_MODE: "1",
    MenuKeys.SWITCH_PHYSICS_2D_MODE: "p",
    MenuKeys.TOGGLE_ROTATION: "n",
    MovementKeys.UP: "w",
    MovementKeys.LEFT: "a",
    MovementKeys.RIGHT: "d",
    MovementKeys.DOWN: "s",
    MovementKeys.FLY_DOWN: "c",
    MovementKeys.FLY_UP: "r",
    DisplayKeys.DECREASE_X_RESOLUTION: "7",
    DisplayKeys.INCREASE_X_RESOLUTION: "8",
    DisplayKeys.DECREASE_Y_RESOLUTION: "9",
    DisplayKeys.INCREASE_Y_RESOLUTION: "0",
    DisplayKeys.SWITCH_RENDERING_MODE: "v",
    DisplayKeys.INCREASE_VISIBILITY: "4",
    DisplayKeys.DECREASE_VISIBILITY: "3",
    DisplayKeys.SWITCH_ANTIALIASING: "?",
    DisplayKeys.DECREASE_FOV: "g",
    DisplayKeys.INCREASE_FOV: "f",
    DisplayKeys.SHUFFLE_COLORS: "m",
    PhysicsKey.RESET_SCENARIO: "r",
    PhysicsKey.RESET_CAMERA: "o",
}
