DEFAULT_VISIBILITY_THRESHOLD = 200
DEFAULT_DISTANCE_TO_SPEC = 100  # controls field of view
PLAYER_3D_MOVING_SPEED_FACTOR = 3

# needed to compensate for the fact that console characters are not square
PIXEL_ASPECT_RATIO = 1.78  



X_RESOLUTION_3D = 180
Y_RESOLUTION_3D = 50

ANTIALIASING_INTENSITY = 0.4

MAX_FPS_3D = 30
